### ISSUE TITLE
Add class prefix to NewWave classes

### ISSUE THREAD

**Issue by noha** [skaplar/NewWave#10]
The class names like Node, Event, etc. are too generic for a system like pharo where there are no namespaces. So introducing class prefixes early might be a good idea. I usually have a few classes like NewWaveEngine named just like that while most other classes would have a NW prefix. But I guess most people out there like consistent naming so everything should be prefixed with NW or what you think is appropriate

**Comment by skaplar** [comment]
Yes, that's a great idea. I have actually thought about it, but didn't find the time yet. I want to finish merging new parts of the system, and I think I'm going to do it after that is finished.
