### ISSUE TITLE
#NewWaveServer is missing, and does not understand #serveOn:waveEngine:

### ISSUE THREAD

**Issue by macta** [skaplar/NewWave#3]
Just loaded the basline and tried one of the examples and I get a walkback "#NewWaveServer is missing, and does not understand #serveOn:waveEngine:"

It looks like the baseline doens't pull in this package?

I also get a complaint about Teapot missing?

I think the baseline needs updating a bit better

**Comment by skaplar** [comment]
Hello, yes I've updated the baseline. Have in mind when running the examples, to call stopEngine when finished to stop the server. I need to update them to a newer version when we finish working on a web functionality.

**Comment by macta** [comment]
I'll try again an fresh P7 image and confirm all is ok

**Comment by noha** [comment]
I loaded the code just now and the NewWaveServer is there. I think this can be closed
