### ISSUE TITLE
TktWorker class is missing?

### ISSUE THREAD

**Issue by macta** [skaplar/NewWave#4]
When I load NewWave and try to run the parallel example I get a walkback as TktWorker is missing?

I think this is again another dependency missing - TaskIt?

UndefinedObject>>doesNotUnderstand: #new
[ | worker |
worker := TKTWorker new.
worker start.
('Starting worker on process '
	, Processor activeProcess identityHash asString) logCr.
('Worker process is ' , worker process identityHash asString) logCr.
wave workers at: worker name put: worker.
wave flowHandler workerid: worker name.
wave tryToExecuteNext: elemToExecute ] in StartEventBehavior>>performExecution:executor: in Block: [ | worker |...
BlockClosure>>cull:
BlockClosure>>cull:cull:
[ action cull: anAnnouncement cull: announcer ] in AnnouncementSubscription>>deliver: in Block: [ action cull: anAnnouncement cull: announcer ]
BlockClosure>>on:do:
[ Processor terminateActive ] in [ :ex | 
| copy onDoCtx process handler bottom thisCtx |
onDoCtx := thisContext.
thisCtx := onDoCtx home.

"find the context on stack for which this method's is sender"
[ onDoCtx sender == thisCtx ]
	whileFalse: [ onDoCtx := onDoCtx sender.
		onDoCtx
			ifNil: [ "Can't find our home context. seems like we're already forked
				and handling another exception in new thread. In this case, just pass it through handler." ^ handlerAction cull: ex ] ].
bottom := [ Processor terminateActive ] asContext.
onDoCtx privSender: bottom.
handler := [ handlerAction cull: ex ] asContext.
handler privSender: thisContext sender.
(Process forContext: handler priority: Processor activePriority)
	resume.

"cut the stack of current process"
thisContext privSender: thisCtx.
nil ] in BlockClosure>>on:fork: in Block: [ Processor terminateActive ]

**Comment by macta** [comment]
I think this is down to loading it in Pharo 8 - the taskit baseline seems to be fixed to V7 and not >= v7 for some reason

**Comment by skaplar** [comment]
That is correct, I didn't have the time to test it in P8 yet, but you can test it in P7.

**Comment by macta** [comment]
I'll test it on P7 and close this
